# If a list item isn't the original build, the pipeline will lift over.
#   If any of the source builds is GRCh38/b38/hg38, the pipeline will error,
#   since UCSC does not provide chain files for hg38 to any build < hg19.
output_builds: [b37, GRCh38]

# Many b37 files are mislabled as hg19 or GRCh37, which causea liftover to fail.
#   This option prevents that by assuming every hg19/b37/GRCh37/HumanG1Kv37
#   file is b37 or HumanG1Kv37.
#
#   If you are sure you have the right build, you can set this to false,
#   otherwise, you can generally assume that files labeled as hg19 or GRCh37 are
#   actually HumanG1Kv37 or b37, which are identical other than the inclusion of
#   an hsv dummy contig (NC_007605). If chromosme 1 is "1", it is one of those,
#   and if chromosme 1 is "chr1", it is hg19 or GRCh37.
#
#   More info here: https://gatk.broadinstitute.org/hc/en-us/articles/360035890711-GRCh37-hg19-b37-humanG1Kv37-Human-Reference-Discrepancies

all_GATK_builds: True

# concatenate at the end? true if so
concatenate: true

inputs:
#  Example:
#    build: hg38
#    # Use {chrom} in the filename to indicate if there are files for each chrom.
#    input_vcf: /path/to/files/some_vcffiles.chr{chrom}.vcf.gz
#    # VCF filter to apply (leave blank or delete for none)
#    filter: 'PASS'
#    # contigs/chromosomes with ranges like 1:22 and other separated by ","
#    #  must be quoted
#    contigs: 1:22,X,Y,MT

  ADNI1microarray:
    build: b36
    # Use {chrom} in the filename to indicate if there are files for each chrom.
    input_vcf: ADNI_cluster_01_forward_757LONI.vcf.gz
    # contigs/chromosomes with ranges like 1:22 and other separated by ","
    #  must be quoted
    contigs: '1:22'
